name: attribution_linker
description: A Flutter package for creating device fingerprints and linking attribution data using WebView. Collect comprehensive device information for analytics and attribution tracking.
version: 1.0.0
homepage: https://github.com/hautran/flutter_attribution_linker
repository: https://github.com/hautran/flutter_attribution_linker
issue_tracker: https://github.com/hautran/flutter_attribution_linker/issues
documentation: https://github.com/hautran/flutter_attribution_linker#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path: ^1.8.0

flutter:
  assets:
    - /assets/

topics:
  - attribution
  - analytics
  - fingerprinting
  - device-info
  - tracking
  - webview