name: attribution_linker
description: A Flutter package for creating device fingerprints and linking attribution data using WebView. Collect comprehensive device information for analytics and attribution tracking.
version: 1.0.1
homepage: https://applink.io.vn/generate.html
repository: https://github.com/hautvfami/attribution_linker
issue_tracker: https://github.com/hautvfami/attribution_linker/issues
documentation: https://github.com/hautvfami/attribution_linker#readme
screenshots:
  - description: The attribution linker logo.
    path: docs/logo.png
funding:
  - https://github.com/sponsors/hautvfami/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path: ^1.8.0

flutter:
  assets:
    - packages/attribution_linker/assets/

topics:
  - attribution
  - analytics
  - fingerprinting
  - tracking
  - webview